*Action Navigation(System.crm Contract Category)
*Action New(crm Contract Category)
*FillForm
 Code = КатДог 1
 Name = Категория дог 1
*Action Save and New(crm Contract Category)
*FillForm
 Code = КатДог 2
 Name = Категория договора 2
*Action Save and New(crm Contract Category)
*FillForm
 Code = КатДог 3
 Name = Категория договора 3
*Action Down Categorys
*Action Down Categorys.New
*FillForm
 Code = КатДог 4
 Name = Кат. дог. 1
*Action Save and Close
