*Action Navigation(System.crm Cost Model)
*Action New(crm Cost Model)
*FillForm
 Code = Мод цены 1
 Name = Модель цены 1
 Description = Мод цены 1 Описание 1
*Action Save and New(crm Cost Model)
*FillForm
 Code = Мод цены 2
 Name = Модель цены 2
 Description = Модель цены 2 Описание 2
*Action Save and New(crm Cost Model)
*FillForm
 Code = Мод цены 3
 Name = Модель цены 3
 Description = Модел ь цены 3 Описание 3
*Action Save
*Action Save and Close
