*Action Navigation(System.cs Unit)
*Action New(cs Unit)
*FillForm
 Code = м
 Name = метр
 Description = Одна сорокотысячная часть длины земного экватора
*Action Save and New(cs Unit)
*FillForm
 Code = кг
 Name = килограмм
 Description = Входит в систему СИ. Мера массы.
*Action Save and New(cs Unit)
*FillForm
 Code = лс
 Name = лошадиная сила
 Description = Применяется в автопромышленности
*Action Save
*Action Save and Close
