*Action Navigation(System.cs Nomenclature Type)
*Action New(cs Nomenclature Type)
*FillForm
 Code = Тип ном 1
 Name = Тип номенклатуры 1
*Action Save and New(cs Nomenclature Type)
*FillForm
 Code = Тип ном 2
 Name = Тип номенклатуры 2
*Action Save and New(cs Nomenclature Type)
*FillForm
 Code = Тип ном 3
 Name = Тип номенклатуры 3
*Action Save and New(cs Nomenclature Type)
*FillForm
 Code = Тип ном 4
 Name = Тип номенклатуры 4
*ExecuteEditorAction Top Type
*FillForm
 Code = Тип ном 1
 Name = Тип номенклатуры 1
*Action OK
*Action Save
*Action Save and Close
