*Action Navigation(System.cs Service)
*Action New(cs Service)
*FillForm
 Nomenclature Type = Тип номенклатуры 2
 Code = Ремонт
 Name Short = Рем
 Name Full = Ремонт всего
 Base Unit = м
 Cost Item = Ст ДДС 1
*Action Save and New(cs Service)
*FillForm
 Nomenclature Type = Тип номенклатуры 1
 Code = Очистка
 Name Short = Очист
 Name Full = Очистка сантехнических коммуникаций :-)
 Base Unit = лс
 Cost Item = Ст ДДС 1
*Action Save
*Action Save and Close
