*Action Navigation(Partners.crm CBusinessman)
*Action New
*Action CommonGroup
*FillForm
 First Name = Мебель
 Last Name = Мебель
 Middle Name = Мебелевич
 Name Handmake = Табуреткин
 INN = 45454545
 Reg Code = 45
 Description = Делает табуретки на коленках
*ExecuteEditorAction Address Legal
*FillForm
 Region = Питерский
 City = Питер
 Zip Postal = 200000
 State Province = Центр
 Street = Фонтанка, 1
*Action OK
*Action Save and New

*Action CommonGroup
*FillForm
 First Name = Застройщик
 Last Name = Застройкин
 Middle Name = Застроевич
 Name Handmake = Землекоп
 INN = 56565656
 Reg Code = 56
 Description = Роет носом как настоящая ищейка
*ExecuteEditorAction Address Fact
*FillForm
 Region = Сибирь
 City = Новосибирск
 Zip Postal = 56565
 State Province = Окраина
 Street = Центральная, 10
*Action OK
*Action Save and Close