*Action Navigation(Partners.Банк)
*Action New
*FillForm
 Name = Банк краж и продаж
 BIC = 1111111
 RCBIC = 22222
 Kor Acc = 4534345234224455654
 Party = Телескопова Астролябия Сектантовна
 Country = РУС
*Action Save and New
*FillForm
 Name = Базовый банк реструктуризации откатов
 BIC = 345554
 RCBIC = 54765756742
 Kor Acc = ук64565434534325235
 Party = Раб Лжецов В.О.
 Country = УКР
*Action Save and New
*FillForm
 Name = Передовой банк поддержки народного хозяйства
 BIC = 3453534546565
 RCBIC = 45765756456
 Kor Acc = 352364756767
 Party =  Бумагоделов П.К.
 Country = БЕЛ
*Action Save and Close
