*Action Navigation(Finance.fm CDirection)
*Action New
*FillForm
 Code = Наука
 Name = Научные разработки
 Name Full = Научные разработки
 Date Begin = 05.12.2011
 Date End = 22.12.2011
 Description = Научные разработки
 Manager = Скоробей Сколопендр Червович
*Action Save and New
*FillForm
 Code = Констр
 Name = Конструкторское бюро
 Name Full = Конструкторское бюро
 Date Begin = 01.12.2011
 Date End = 15.12.2011
 Description = Конструкторское бюро
 Manager = Муравей Ломехуза Тараканович
*Action Save and New
*FillForm
 Code = Экономика
 Name = Экономические исследования
 Name Full = Экономические исследования
 Date Begin = 05.12.2011
 Date End = 17.12.2011
 Description = Экономические исследования
 Manager = Скоробей Сколопендр Червович
*Action Save and Close
