*Action Navigation(System.cs Country)
*Action New
*FillForm
 Name En Short Low = RUS
 Name En Full = RUSSIA
 Name Ru Short Low = РУС
 Name Ru Full = РОССИЯ
 Code Alfa 2 = RU
 Code Alfa 3 = Rus
 Code Ru Alfa 3 = Рус
 Code Numeric = 001
 Comment = РОССИЯ
*Action Save and New
*FillForm
 Name En Short Low = UA
 Name En Full = UA
 Name Ru Short Low = УКР
 Name Ru Full = УКРАИНА
 Code Alfa 2 = UA
 Code Alfa 3 = Ua
 Code Ru Alfa 3 = УКР
 Code Numeric = 002
 Comment = УКРАИНА
*Action Save and New
*FillForm
 Name En Short Low = BY
 Name En Full = BY
 Name Ru Short Low = БЕЛ
 Name Ru Full = БЕЛОРУССИЯ
 Code Alfa 2 = BY
 Code Alfa 3 = By
 Code Ru Alfa 3 = БЕЛ
 Code Numeric = 003
 Comment = БЕЛОРУССИЯ
*Action Save and Close