*Action Navigation(Partners.crm CParty)
*Action New(crm CParty)
*FillForm
 Name = Продавец воздуха
 Name Full = Метеоролог
 INN = 56434645567
 KPP = 54665734
 Description = Гадает на погоде
*ExecuteEditorAction Address Fact
*FillForm
 Region = Австралия
 City = Кенгуру-сити
 Zip Postal = 565467657
 State Province = Западная Австралия
 Street = Крокодиловая, 5
*Action OK
*ExecuteEditorAction Address Post
*FillForm
 Region = Австралия
 City = Южнокенгурятинск
 Zip Postal = 7876865754
 State Province = Южная Австралия
 Street = Миклухо-Маклая, 10
*Action OK
*Action Save and New(crm CParty)
*FillForm
 Name = И
 Description = нтеллигент
 Name = Интеллигент Голый
 Description = Интеллигент Голый
 Name Full = Интеллигент Голый
 INN = 45545445
 KPP = 7785654
*ExecuteEditorAction Address Fact
*FillForm
 Region = БОМЖ
 City = БОМЖ
 Zip Postal = -------
 State Province = БОМЖ
 Street = БОМЖ
*Action OK
*Action Save and New(crm CParty)
*FillForm
 Name = Шляпная фабрика
 Name Full = Шляпная фабрика
 Description = Шляпная фабрика
 INN = 34545345
 KPP = 8767867
*ExecuteEditorAction Address Fact
*FillForm
 Region = Московский
 City = Москва
 Zip Postal = 5464534
 State Province = Кремль
 Street = Красная площадь, 1
*Action OK
*Action Save and Close
