*Action Navigation(System.cs Material)
;*Action New
*Action New
*FillForm
 Code = Железо
 Name Short = Железо
 Name Full = Железо
 Base Unit = Кг
 Nomenclature Type = Металлы
*ExecuteEditorAction Cost Item
*Action New
*FillForm
 Code = CIt1
 Name = Cost Item 1
 Description = Cost Item 1
*Action Save and Close
*Action Save and New
*FillForm
 Code = Свинец
 Name Short = Свинец
 Name Full = Свинец
 Base Unit = Кг
 Nomenclature Type = Финансы
*ExecuteEditorAction Cost Item
*Action New
*FillForm
 Code = CIt2
 Name = Cost Item 2
 Description = Cost Item 2
*Action Save and Close
*Action Save and New
*FillForm
 Code = Брюки
 Name Short = Брюки
 Name Full = Брюки
 Base Unit = Кг
 Nomenclature Type = Тряпьё
*ExecuteEditorAction Cost Item
*Action New
*FillForm
 Code = CIt3
 Name = Cost Item 3
 Description = Cost Item 3
*Action Save and Close
*Action Save and Close