*Action Navigation(System.cs Valuta)
*Action New
*FillForm
 Code = RUR
 Name Short = Руб.
 Name Full = Рубль
 Base Unit = руб.
 Cost Item = CIt1
 Nomenclature Type = Финансы
*Action Save and New
*FillForm
 Code = EUR
 Name Short = евро
 Name Full = евро
 Base Unit = руб.
 Cost Item = CIt2
 Nomenclature Type = Финансы
*Action Save and New
*FillForm
 Code = USD
 Name Short = бак
 Name Full = доллар
 Base Unit = руб.
 Cost Item = CIt3
 Nomenclature Type = Финансы
*Action Save and Close