*Action Navigation(Partners.crm CPhysical Party)
*Action New
*Action CommonGroup
*FillForm
 First Name = Астролябов
 First Name = Астролябия
 Last Name = Телесоп
 Last Name = Телескопова
 Middle Name = Сектантовна
 INN = 77890543
 Description = Тётка астрономичка
*Action Save and New
*Action CommonGroup
*FillForm
 First Name = Свекла
 Last Name = Брюквакова
 Middle Name = Картофелевна
 INN = 7576576565
 Description = Специалистка по сельскому хозяйству
*Action Save and New
*Action CommonGroup
*FillForm
 First Name = Затычка
 Last Name = Сантехова
 INN = 65645632
 Description = Дипломированая специалистка по ремонту сантехники
*Action Save and Close
