*Action Navigation(System.cs Service)
*Action New
*FillForm
 Code = Кормл
 Name Short = Кормление
 Name Full = Кормление
 Base Unit = л
 Nomenclature Type = Финансы
 Cost Item = CIt1
*Action Save and New
*FillForm
 Code = Чистка
 Name Short = Хим чистка
 Name Full = Химическая чистка
 Base Unit = л
 Cost Item = CIt2
 Nomenclature Type = Финансы
*Action Save and New
*FillForm
 Code = Рем
 Name Short = Ремонт
 Name Full = Ремон инженерных сетей
 Base Unit = руб.
 Cost Item = CIt3
 Nomenclature Type = Финансы
*Action Save and Close