*Action Navigation(Finance.fm CSubject)
*Action New
*FillForm
 Code = Subj1
 Name = Subject 1
 Name Full = Subject 1
 Date Begin = 06.12.2011
 Date End = 25.12.2011
 Description = Subject 1
 Direction = Конструкторское бюро
*Action Save and New
*FillForm
 Code = Subj2
 Name = Subject 2
 Name Full = Subject 2
 Date Begin = 07.12.2011
 Date End = 31.12.2011
 Description = Subject 1
 Direction = Конструкторское бюро
*Action Save and New
*FillForm
 Code = Subj3
 Name = Subject 3
 Name Full = Subject 3
 Date Begin = 15.12.2011
 Date End = 30.12.2011
 Description = Subject 3
 Direction = Научные разработки
*Action Save and Close
