*Action Navigation(Partners.crm CLegal Person)
*Action New
*FillForm
 Name = Дуб дубом и Ко
*Action CommonGroup
*FillForm
 INN = 45454445
 KPP = 232342342
 Reg Code = 3466
 Person Type = Рабочий скот
*ExecuteEditorAction Address Legal
*FillForm
 Region = Западная Европа
 City = Париж
 Zip Postal = 2454554
 State Province = Рядом с Эйфелевой башней
 Street = Монмартр
*Action OK
*ExecuteEditorAction Address Fact
*FillForm
 Region = Дальний Восток
 City = Владивосток
 Zip Postal = 1232354565
 State Province = Сахалин
 Street = Портовая, 1
*Action OK
*Action Save and New
*Action CommonGroup
*ExecuteEditorAction Person Type
*FillForm
 Name = Торговцы воздухом и сыновья
 INN = 54344354
 KPP = 5465464523
 Reg Code = 12
*ExecuteEditorAction Address Legal
*FillForm
 Region = Северная Америка
 City = Вашингтон
 Zip Postal = 12334
 Street = Обкомовская, 3
*Action OK
*ExecuteEditorAction Address Fact
*FillForm
 Region = Антарктида
 City = Пуп Земли
 Zip Postal = 3453456546
 State Province = Циркумполярная зона
 Street = Ледяная, 1
*Action OK
*Action Save and New
*FillForm
 Name = Фирма братьев Карамазовых
*Action CommonGroup
*FillForm
 INN = 345355
 KPP = 4534345
 Reg Code = 334546
 Description = Инструкцию по применению см. в романе Достоевского Братва Карамазова 
 Person Type = Работник
*ExecuteEditorAction Address Legal
*FillForm
 Region = Северный
 City = Санкт-Петербург
 Zip Postal = 2342344554
 State Province = Залив
 Street = Невский проспект, 3
*Action OK
*ExecuteEditorAction Address Fact
*FillForm
 Region = Северный
 City = Земля Франца Иосифа
 Zip Postal = 5475675434
 State Province = Каменоломня
 Street = Сидельцев, 100
*Action OK
*Action Save and Close