;*Action OK
*Action Navigation(Системные.Категория договора)
*Action New(Категория договора)
*FillForm
 Код = Кат. дог. 1
 Наименование = Категория дог 1
*Action Save and New(Категория договора)
*FillForm
 Код = Кат. дог. 2
 Наименование = Категория договора 2
*Action Save and New(Категория договора)
*FillForm
 Код = Кат. дог. 3
 Наименование = Категория договора 3
*Action Подкатегории
*Action Подкатегории.New
*FillForm
 Код = Кат. дог. 4
 Наименование = Кат. дог. 1
*Action Save and Close
*Action Save and Close
