;*Action OK
*Action Navigation(Системные.Модель цены)
*Action New(Модель цены)
*FillForm
 Код = Мод цены 1
 Наименование = Модель цены 1
 Описание = Мод цены 1 Описание 1
*Action Save and New(Модель цены)
*FillForm
 Код = Мод цены 2
 Наименование = Модель цены 2
 Описание = Модель цены 2 Описание 2
*Action Save and New(Модель цены)
*FillForm
 Код = Мод цены 3
 Наименование = Модель цены 3
 Описание = Модел ь цены 3 Описание 3
*Action Save
*Action Save and Close
