*Action Navigation(Системные.Страна)
*Action New(Страна)
*FillForm
 En Короткое имя = RUS
 En Полное имя = Russia
 En Короткое имя = Rus
 Ru Короткое имя = РФ
 Ru Полное имя = РОССИЯ
 Букв2С = RU
 Букв3С = RUS
 Рус3C = Рус
 Цифровой = 001
 Комментарий = Российская федерация
*Action Save and New(Страна)
*FillForm
 En Короткое имя = BY
 En Полное имя = BY
 Ru Короткое имя = РБ
 Ru Полное имя = РЕСПУБЛИКА БЕЛОРУСЬ
 Букв2С = BY
 Букв3С = BY
 Рус3C = РБ
 Цифровой = 002
 Комментарий = РЕСПУБЛИКА БЕЛОРУСЬ
*Action Save and New(Страна)
*FillForm
 En Короткое имя = UKR
 En Полное имя = Ukraine
 Ru Короткое имя = УКР
 Ru Полное имя = УКРАИНА
 Букв2С = UK
 Букв3С = UKR
 Рус3C = УКР
 Цифровой = 003
 Комментарий = УКРАИНА
*Action Save
*Action Save and Close
