*Action Navigation(Системные.cs Material)

*Action New(cs Material)
*FillForm
 Категория = Тип номенклатуры 1
 Код = Сталь
 Сокр.Наимен. = Ст
 Наименование = Сталь углеродистая
 Баз.Ед.Изм. = кг
*ExecuteEditorAction Статья ДДС
*Action New(Статья ДДС)
*FillForm
 Код = Ст ДДС 1
 Наименование = Статья ДДС 1
 Описание = Статья ДДС 1
*Action Save and Close
*Action Save and New(cs Material)
*FillForm
  Категория = Тип номенклатуры 2
  Код = H2O
  Сокр.Наимен. = Вода
  Наименование = Вода дистилированная
  Баз.Ед.Изм. = кг
*ExecuteEditorAction Статья ДДС
*Action New(Статья ДДС)
*FillForm
 Код = Ст ДДС 2
 Наименование = Статья ДДС 2
 Описание = Статья ДДС 2
*Action Save and Close
*Action Save and Close
