*Action Navigation(Системные.cs Valuta)

*Action New(cs Valuta)
*FillForm
 Код = Curr
 Сокр.Наимен. = Вал
 Наименование = Валюта
*Action Save and New(cs Valuta)

*FillForm
 Код = Руб
 Сокр.Наимен. = Руб
 Наименование = Рубль
*Action Save and New(cs Valuta)

*FillForm
 Код = USD
 Сокр.Наимен. = USD
 Наименование = Доллар
*Action Save and New(cs Valuta)

*FillForm
 Код = EUR
 Сокр.Наимен. = EUR
 Наименование = Евро
*Action Save
*Action Save and Close
