*Action Navigation(System.cs Country)
*Action New(cs Country)
*FillForm
 Name En Short Low = RUS
 Name En Full = Russia
 Name Ru Short Low = РФ
 Name Ru Full = РОССИЯ
 Code Alfa 2 = RU
 Code Alfa 3 = RUS
 Code Ru Alfa 3 = Рус
 Code Numeric = 001
 Comment = Российская федерация
*Action Save and New(cs Country)
*FillForm
 Name En Short Low = BY
 Name En Full = BY
 Name Ru Short Low = РБ
 Name Ru Full = РЕСПУБЛИКА БЕЛОРУСЬ
 Code Alfa 2 = BY
 Code Alfa 3 = BY
 Code Ru Alfa 3 = РБ
 Code Numeric = 002
 Comment = РЕСПУБЛИКА БЕЛОРУСЬ
*Action Save and New(cs Country)
*FillForm
 Name En Short Low = UKR
 Name En Full = Ukraine
 Name Ru Short Low = УКР
 Name Ru Full = УКРАИНА
 Code Alfa 2 = UK
 Code Alfa 3 = UKR
 Code Ru Alfa 3 = УКР
 Code Numeric = 003
 Comment = УКРАИНА
*Action Save
*Action Save and Close
