*Action Navigation(System.cs Material)
*Action New(cs Material)
*FillForm
 Nomenclature Type = Тип номенклатуры 1
 Code = Сталь
 Name Short = Ст
 Name Full = Сталь углеродистая
 Base Unit = кг
*ExecuteEditorAction Cost Item
*Action New
*FillForm
 Code = Ст ДДС 1
 Name = Статья ДДС 1
 Description = Статья ДДС 1
*Action Save and Close
*Action Save and New(cs Material)
*FillForm
  Nomenclature Type = Тип номенклатуры 2
  Code = H2O
  Name Short = Вода
  Name Full = Вода дистилированная
  Base Unit = кг
*ExecuteEditorAction Cost Item
*Action New
*FillForm
 Code = Ст ДДС 2
 Name = Статья ДДС 2
 Description = Статья ДДС 2
*Action Save and Close
*Action Save and Close
