*Action Navigation(System.cs Valuta)
*Action New(cs Valuta)
*FillForm
 Nomenclature Type = Тип номенклатуры 2
 Code = Gold
 Name Short = Злато
 Name Full = Золото
 Base Unit = кг
 Cost Item = Ст ДДС 1
*Action Save and New(cs Valuta)

*FillForm
 Nomenclature Type = Тип номенклатуры 2
 Code = Руб
 Name Short = Руб
 Name Full = Рубль
 Base Unit = кг
 Cost Item = Ст ДДС 1
*Action Save and New(cs Valuta)

*FillForm
 Nomenclature Type = Тип номенклатуры 2
 Code = USD
 Name Short = USD
 Name Full = Доллар
 Base Unit = кг
 Cost Item = Ст ДДС 1
*Action Save and New(cs Valuta)

*FillForm
 Nomenclature Type = Тип номенклатуры 2
 Code = EUR
 Name Short = EUR
 Name Full = Евро
 Base Unit = кг
 Cost Item = Ст ДДС 1
*Action Save
*Action Save and Close
