*Action Navigation(Partners.Юридическое лицо)
*Action New(Юридическое лицо)
*FillForm
 Name = Асфальто-бетонный завод
*ExecuteEditorAction Address
*FillForm
 Zip Postal = 234000
 State Province = Северо-западный
 City = Чехов
 Street = Белые столбы
 Region = Чеховский
*Action OK
*FillForm
 INN = 333444555
 Reg Number = а234
 Name Full = Асфальто-бетонный завод по производству асфальта и бетона, отгрохотки и прочего
*Action Save and New(Юридическое лицо)
*FillForm
 Name = ИнтекоАГ
*ExecuteEditorAction Address
*FillForm
 Zip Postal = 333000
 State Province = Москва
 City = Москва
 Street = Бумажный проезд, 4
*Action OK
*FillForm
 INN = 1212312
 Reg Number = 3434
 Name Full = ИнтекоАГ
*Action Save
*Action Save and Close
