*Action Navigation(Finance.fm Abstract Subject)
*Action New(fm Direction)
*FillForm
 Code = Тема 1
 Name = Разработка аппарата имитации человека разумного
 Date Begin = 03.10.2011
 Date End = 10.10.2011
*Action Save and New(fm Direction)
*FillForm
 Code = Тема 2
 Name = Исследование глубокого космоса с привлечением Кашпировского и Чумака
 Date Begin = 24.10.2011
 Date End = 28.10.2011
*Action Save
*Action Save and Close
