*Action Navigation(Finance.fm CSubject)
*Action New
*FillForm
 Code = Тема 1
 Name = Разработка аппарата имитации человека разумного
 Name Full = Разработка аппарата имитации человека разумного
 Date Begin = 22.12.2011
 Date End = 22.12.2011
 Description = Разработка аппарата имитации человека разумного
*ExecuteEditorAction Direction
*Action New
*FillForm
 Code = Физ 1
 Name = Физические свойства абсолютной материи
 Name Full = Физические свойства абсолютной материи
 Date Begin = 22.12.2011
 Date End = 22.12.2011
 Description = Физические свойства абсолютной материи
*ExecuteEditorAction Manager
*Action New
*FillForm
 Level = 1
 Last Name = Скоробей
 First Name = Таракан
 Middle Name = Сколопендрович
*ExecuteEditorAction Department
*Action New
*FillForm
 Code = Dep1
 Buh Code = BuhDep1
 Post Code = 111222
 Name = Отдел роспила
*Action Save and Close
*Action Save and Close
*Action Save and Close
*Action Save and New

; Следующая запись
*FillForm
 Code = Тема 2
 Name = Всасывающий патрубок и его клоны
 Name Full = Всасывающий патрубок и его клоны
 Date Begin = 30.12.2011
 Date End = 30.12.2011
 Description = Всасывающий патрубок и его клоны
*ExecuteEditorAction Direction
*Action New
*FillForm
 Code = СОС 2
 Name = Разработка аппарата глубокого сосания
 Name Full = Физические свойства абсолютной материи
 Date Begin = 30.12.2011
 Date End = 30.12.2011
 Description = Физические свойства абсолютной материи
*ExecuteEditorAction Manager
*Action New
*FillForm
 Level = 1
 Last Name = Осьминог
 First Name = Кальмар
 Middle Name = Акулович
*ExecuteEditorAction Department
*Action New
*FillForm
 Code = Dep2
 Buh Code = BuhDep2
 Post Code = 111333
 Name = Отдел откатов
*Action Save and Close
*Action Save and Close
*Action Save and Close
*Action Save and Close