*Action Navigation(Staffs.hrm Staff)
*Action New(hrm Staff)
*FillForm
 Last Name = Путин
 First Name = Владимир
 Middle Name = Владимирович
 Department = Отд 1
 Level = Главный
*Action Save and New(hrm Staff)
*FillForm
 Last Name = Медведев
 First Name = Дмитрий
 Middle Name = Анатольевич
 Department = АДМ 1
 Level = Президент
*Action Save and New(hrm Staff)
*FillForm
 Last Name = Зюганов
 First Name = Геннадий
 Middle Name = Андреевич
 Department = ЦПП
 Level = Заготовитель электората
*Action Save
*Action Save and Close
