*Action Navigation(Contract.crm Contract Registration Form)
*FillForm
 User Registrator = Путин Владимир Владимирович
*ExecuteEditorAction Document Category
*Action New
*FillForm
 Code = Тип дог 1
 Name = Договор подряда
*Action Save and Close
*FillForm
 New Number Required = True
 Kind Of Deal = DEAL_WITHOUT_STAGE
 Category = Кат. дог. 2
 Curator Department = ЦПП
 Price = 2220
 Valuta = Руб
 Date Begin = 18.10.2011
 Date End = 18.10.2011
 Date Finish = 28.10.2011
 Description Short = Договор о воздержании от договоров
 Our Role = CUSTOMER
 Our Party = ИнтекоАГ
 Partner Party = ИнтекоАГ
*Action Wizard Support Complete Action
*Action Save and Close
